name: spotyland
description: Simulacion de Spotify.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  audioplayers: ^6.1.0

  cupertino_icons: ^1.0.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  http: ^1.2.2 
  flutter_dotenv: ^5.2.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/avatars/
    - assets/artistas/
    - assets/canciones/
    - assets/mp3/
    - assets/.env
